#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.8.0
# Product:       slf3x
# Model-Version: 2.0.1
#
"""
The class Slf3xDeviceBase implements the low level interface of the sensor.
The class Slf3xDevice extends the Slf3xDeviceBase. It provides additional functions to ease the use of the
sensor.
"""

from sensirion_driver_adapters.transfer import execute_transfer
from sensirion_driver_support_types.mixin_access import MixinAccess
from sensirion_i2c_slf3x.commands import (ReadMeasurementDataRaw, ReadProductIdentifier, ReadProductIdentifierPrepare,
                                          ReadThermalConductivityMeasurementData, SignalingFlagsT,
                                          StartH2oContinuousMeasurement, StartIpaContinuousMeasurement,
                                          StartSingleThermalConductivityMeasurementAsync,
                                          StartSingleThermalConductivityMeasurementSync,
                                          StopContinuousMeasurement)

from sensirion_i2c_slf3x.result_types import (SignalDeltaTemperature, SignalFlow, SignalTemperature,
                                              SignalThermalConductivity)


class Slf3xDeviceBase:
    """Low level API implementation of SLF3X"""

    def __init__(self, channel):
        self._channel = channel

    @property
    def channel(self):
        return self._channel

    def start_h2o_continuous_measurement(self):
        """
        Starts continuous measurement mode using calibration values for H₂O.
        The sensor measures both the flow rate and the temperature. After the command has been sent, the chip
        continuously measures and updates the measurement results which can be read with *read_measurement_data_raw*.

        .. note::
            The first measurement result will be available after 12ms. Due to the thermal measurement principle small
            accuracy deviations (% m.v.) can occur while the sensor warms-up (60ms including the 12 ms for measurement initialization).
        """
        transfer = StartH2oContinuousMeasurement()
        return execute_transfer(self._channel, transfer)

    def start_ipa_continuous_measurement(self):
        """
        Starts continuous measurement mode using calibration values for Isopropyl alcohol.
        The sensor measures both the flow rate and the temperature. After the command has been sent, the chip
        continuously measures and updates the measurement results which can be read with *read_measurement_data_raw*.

        .. note::
            The first measurement result will be available after 12ms. Due to the thermal measurement principle small
            accuracy deviations (% m.v.) can occur while the sensor warms-up (60ms including the 12 ms for measurement initialization).
        """
        transfer = StartIpaContinuousMeasurement()
        return execute_transfer(self._channel, transfer)

    def read_measurement_data_raw(self):
        """
        After the command *start_xx_continuous_measurement* has been sent, the chip continuously measures and updates
        the measurement results. New results (flow, temperature, and signaling flags) can be read continuously
        with this command.

        :return raw_flow:
            For SLF3C-1300F, SLF3S-1300F convert to ml/min by applying: flow = raw_flow / 500
            For SLF3S-4000B convert to ml/min by applying: flow = raw_flow / 32
            For SLF3S-0600F convert to μl/min by applying: flow = raw_flow / 10
        :return raw_temperature:
            Convert to degrees celsius by temperature = raw_temperature / 200
        :return signaling_flags:
            Gives additional information about the measurement status. Refer to the
            sensor data sheet for detailed information. Following flags are defined:
            Air-in-Line flag (Bit 0), High Flow flag (Bit 1), Exponential smoothing active (Bit 5)

        .. note::
            The first measurement result will be available 12ms after starting the measurement.
            Small accuracy deviations (% m.v.) can occur during the first 60ms (including the 12ms initialization)
        """
        transfer = ReadMeasurementDataRaw()
        res_0, res_1, res_2 = execute_transfer(self._channel, transfer)
        return res_0, res_1, SignalingFlagsT(res_2)

    def stop_continuous_measurement(self):
        """
        This command stops the continuous measurement and puts the sensor in idle mode.
        After it receives the stop command, the sensor needs up to 0.5ms to power down the heater,
        enter idle mode and be receptive for a new command.
        """
        transfer = StopContinuousMeasurement()
        return execute_transfer(self._channel, transfer)

    def start_single_thermal_conductivity_measurement_sync(self):
        """
        This command starts one thermal conductivity measurement and blocks for 2.3 seconds
        until the measurement results are ready.
        After completion of the measurement, the heater is switched off and the sensor enters idle mode and the results
        can be read anytime with *read_thermal_conductivity_measurement_data*.
        The sensor measures the thermal conductivity, the sensor temperature, and the
        delta-temperature (a measure for the temperature difference between the liquid and the sensor).
        Supported by products: SLF3C-1300F, SLF3S-4000B
        """
        transfer = StartSingleThermalConductivityMeasurementSync()
        return execute_transfer(self._channel, transfer)

    def start_single_thermal_conductivity_measurement_async(self):
        """
        This command starts one thermal conductivity measurement and returns immediately.
        Note that the sensor does not accept any other commands while the measurement is running, which takes
        approximately 2.3 seconds.
        After completion of the measurement, the heater is switched off and the sensor enters idle mode and the results
        can be read anytime with *read_thermal_conductivity_measurement_data*.
        The sensor measures the thermal conductivity, the sensor temperature, and the
        delta-temperature (a measure for the temperature difference between the liquid and the sensor).
        Supported by products: SLF3C-1300F, SLF3S-4000B
        """
        transfer = StartSingleThermalConductivityMeasurementAsync()
        return execute_transfer(self._channel, transfer)

    def read_thermal_conductivity_measurement_data(self):
        """
        Reads single thermal conductivity measurement after a measurement has been started with
        *start_single_thermal_conductivity_measurement_sync* or *start_single_thermal_conductivity_measurement_async*.
        Supported by products: SLF3C-1300F, SLF3S-4000B

        :return thermal_conductivity:
            thermal conductivity
        :return raw_temperature:
            Convert to degrees celsius by temperature = raw_temperature / 200
        :return raw_delta_temperature:
            The delta-temperature is a measure for the temperature difference between the liquid and the sensor.
            Convert to degrees celsius by delta_temperature = raw_delta_temperature / 1000
        """
        transfer = ReadThermalConductivityMeasurementData()
        return execute_transfer(self._channel, transfer)

    def read_product_identifier_prepare(self):
        """
        Prepare to read the product identifier and the serial number.
        The command can only be executed from the idle mode, i.e. when the sensor is not performing measurements.
        """
        transfer = ReadProductIdentifierPrepare()
        return execute_transfer(self._channel, transfer)

    def read_product_identifier(self):
        """
        This command allows to read product identifier and the serial number.
        The command can only be executed from the idle mode, i.e. when the sensor is not performing measurements
        and *read_product_identifier_prepare* is called before.

        :return product_identifier:
            Note that the last 8 bits are the sensor’s revision number and are subject to change in case of an
            update of the specifications.
        :return serial_number_high:
            Higher 32-bit of the 64-bit unique serial number
        :return serial_number_low:
            Lower 32-bit of the 64-bit unique serial number
        """
        transfer = ReadProductIdentifier()
        return execute_transfer(self._channel, transfer)


class Slf3xDevice(Slf3xDeviceBase):
    """Driver class implementation of SLF3X"""

    #: Access to base class
    slf3x = MixinAccess()

    def __init__(self, channel):
        super().__init__(channel)

    def read_measurement_data(self, inv_flow_scale_factor):
        """
        Reads the raw measurement values and converts them to their physcial units where applicable.
        For the flow the scaling factor and resulting flow unit depends on the specific sensor.
        The scaling factor is passed as an argument and the raw flow value is converted by applying:
        flow = raw_flow / inv_flow_scale_factor
        The scaling factors for the supported sensor are defined in enum *inv_flow_scale_factors*

        :param inv_flow_scale_factor:
            used to convert raw flow value

        :return a_flow:
            As the flow scaling differs for specific sensor types the scaling factor
            must be passed as an argument. See the enum *inv_flow_scale_factors* for
            scaling factors of supported sensors.
            The raw value is converted by: flow = raw_flow / inv_flow_scale_factor
            Resulting unit depends on your specific sensor type.
        :return a_temperature:
            temperature in degree celsius
        :return a_signaling_flags:

        """
        (raw_flow, raw_temp, signaling_flags
         ) = self.slf3x.read_measurement_data_raw()
        return (SignalFlow(raw_flow, inv_flow_scale_factor), SignalTemperature(raw_temp), signaling_flags)

    def read_thermal_conductivity_measurement_data(self):
        """
        Reads single thermal conductivity measurement after a measurement has been started with
        *start_single_thermal_conductivity_measurement*.
        Supported by products: SLF3C-1300F, SLF3S-4000B

        :return a_thermal_conductivity:
            thermal conductivity in arbitary unit
        :return a_temperature:
            temperature in degree celsius
        :return a_delta_temperature:
            delta temperature in degree celsius
        """
        (th_cond, raw_temp, raw_delta_temp
         ) = self.slf3x.read_thermal_conductivity_measurement_data()
        return (SignalThermalConductivity(th_cond), SignalTemperature(raw_temp),
                SignalDeltaTemperature(raw_delta_temp))

    def read_product_identifier(self):
        """
        Read product identifier and the serial number.
        The command can only be executed from the idle mode, i.e. when the sensor is not performing measurements.

        :return product_identifier:

        :return serial_number:

        """
        self.slf3x.read_product_identifier_prepare()
        (product_id, serial_number_high, serial_number_low
         ) = self.slf3x.read_product_identifier()
        return (product_id, (int(serial_number_high) * 4294967296) + serial_number_low)
